apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-rg4w
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0063-tenant/tkrw-pr712-0075-0063-app/devfile-sample-rg4w@sha256:71526067fc3993e833f92f48cfb204b835177fe24f444eb5f1f07487f0c8cb62
        name: my-nodejs
        resources: {}
status: {}
